#!/bin/bash
#
# Title: AIR Project Compiler
# Usage: ./compile
# Copyright: 2014 Adrian C. Miranda
# License: Apache License
# Version: 0.0.1
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FLEX_SDK="/Applications/Utilities/SDKs/ApacheFlexSDK4";
$compc="$FLEX_SDK/bin/compc";
$compc -help list;
