#!/bin/bash
#
# Title: AIR Project Compiler
# Usage: ./compile
# Copyright: 2014 Adrian C. Miranda
# License: Apache License
# Version: 0.0.1
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SYM: For reading through a symlink, which is usually not what you want
# (you usually don't want to confuse the user this way)
local SYM=$(basename "$(test -L "$0" && readlink "$0" || echo "$0")");
local DIR=$(dirname "$0");
local PWD=$(pwd);
local ABS=$(cd "$DIR"; pwd);

# Config
local FLEX_SDK="/Applications/Utilities/SDKs/ApacheFlexSDK4";
local CONFIG="-namespace http://www.adobe.com/$(date +%Y)/AM manifest.xml";
local compc="$FLEX_SDK/bin/compc";

# Status
local BCya='\e[1;36m';
local NC='\e[0m';
printf "${BCya}Running $SYM symlink on GNU bash $BASH_VERSION${NC}\n";
printf "${BCya}From:${NC} $PWD\n";
printf "${BCya}Origin:${NC} $ABS\n";

# Execution
PACKAGE="";
RESOURCES="";
CONFIG="$CONFIG -source-path ${1:$ABS/source}";
CONFIG="$CONFIG -output='$ABS/dist/am.swc'";
CONFIG="$CONFIG -include-namespaces http://www.adobe.com/$(date +%Y)/AM";
CONFIG="$CONFIG -include-classes $PACKAGE";
CONFIG="$CONFIG -include-file $RESOURCES";
$compc $CONFIG;
